# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afa70346779932df9fa359271228b12a0140c064214fe3a4f1dffa1a9c23231f751dd7e9b6b7337234e63a263588d0e32a7bc5852c2fbc4dcbde980bb689112

test:
  secret_key_base: 6aef616070980003784e93d23afadabde21bb0ad1959ae073bcd22ede630e6a5e07bbefff7f07dd0859a736d8af4306be49347b761d44e29b784661924bfd56b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
